### ISSUE TITLE
Error for many mp3-files: FFAudioSource: No audio track found

### ISSUE THREAD

**Issue by kaefert** [avxsynth/avxsynth#107]
The included FFMS2 source filter gives this error for about 2 out of 3 of my mp3 files:

[ffmpeg/audio] mp3: incomplete frame
[ffmpeg/demuxer] avisynth: FFAudioSource: No audio track found
[ffmpeg/demuxer] \(Script.avs, line 118)
[lavf] avformat_open_input() failed
Failed to recognize file format.

(this error cancels processing of the script for me.)

Sample MP3 that causes this error for me:
https://drive.google.com/file/d/0B1NjqVsz57PXUmUwTlJyNVpJNXdVTjQ0dE5FQUdIZGFxcHln

**Comment by kaefert** [comment]
those mp3 files causing this issue play fine in every other player

**Comment by avxsynth-testing** [comment]
This is almost certainly not a defect in AvxSynth. Please report this to ffms2.
