### ISSUE TITLE
Fail build in linux (probably incompatible with jpeg-turbo 1.4.0)

### ISSUE THREAD

**Issue by sl1pkn07** [avxsynth/avxsynth#111]
Hi. fail build on linux

http://sl1pkn07.wtf/paste/view/5a9ecf1e

greetings

**Comment by 5shekel** [comment]
bump

**Comment by qyot27** [comment]
So build against an older version of libjpeg-turbo or disable the avxframecapture plugin.  The plugin is where the failure is, not in the core.

**Comment by 5shekel** [comment]
hey, how do you disable said plugin during make?

**Comment by qyot27** [comment]
You disable it during configure (likely --disable-framecapture, check ./configure --help to see what the actual option is).

**Comment by sl1pkn07** [comment]
any plans to update for latest libjpeg-turbo?

**Comment by emanueLczirai** [comment]
Pasting here to facilitate finding this when searching within Issues:

<p>Making all in plugins/avxframecapture<br />
make[1]: Entering directory '/home/emacs/build/avxsynth-git/makepkg/avxsynth-git/src/avxsynth/plugins/avxframecapture'<br />
CXX src/libavxframecapture_la-FrameRenderer.lo<br />
In file included from src/FrameRenderer.cpp:70:0:<br />
/usr/include/jerror.h:137:1: error: ‘JCOPYRIGHT_SHORT’ was not declared in this scope<br />
JMESSAGE(JMSG_COPYRIGHT, JCOPYRIGHT_SHORT)<br />
^<br />
Makefile:505: recipe for target 'src/libavxframecapture_la-FrameRenderer.lo' failed<br />
make[1]: *** [src/libavxframecapture_la-FrameRenderer.lo] Error 1<br />
make[1]: Leaving directory '/home/emacs/build/avxsynth-git/makepkg/avxsynth-git/src/avxsynth/plugins/avxframecapture'<br />
Makefile:500: recipe for target 'all-recursive' failed<br />
make: *** [all-recursive] Error 1</p>

**Comment by avxsynth-testing** [comment]
Can someone distill what is actually needed to fix the compilation issue (if any) into a patch? Thanks.
