### ISSUE TITLE
adding black borders without overlay?

### ISSUE THREAD

**Issue by kaefert** [avxsynth/avxsynth#112]
is there some way in avxsynth to add black borders?

In avisynth I use BlankClip() and Overlay, for example:

    bl = a.BlankClip
    b = b.ConvertToRGB.Crop(0,7,640,344).Lanczos4Resize(693,393)
    b = bl.Overlay(b,3,5)

But sadly Overlay seems to not have been ported to avxsynth, see also
https://github.com/avxsynth/avxsynth/issues/32

So is there any way to do something simple like adding black borders without Overlay?

**Comment by avxsynth-testing** [comment]
Does the AddBorders function not work?

**Comment by kaefert** [comment]
yes it does, sorry I did not know the function exists when I asked this question. It seems I've unintentionally created this issue twice, I already got my answer long ago here:
