### ISSUE TITLE
adding black borders without overlay?

### ISSUE THREAD

**Issue by kaefert** [avxsynth/avxsynth#113]
is there some way in avxsynth to add black borders?

In avisynth I use BlankClip() and Overlay, for example:

    bl = a.BlankClip
    b = b.ConvertToRGB.Crop(0,7,640,344).Lanczos4Resize(693,393)
    b = bl.Overlay(b,3,5)

But sadly Overlay seems to not have been ported to avxsynth, see also
https://github.com/avxsynth/avxsynth/issues/32

So is there another way to do something simple like adding black borders then Overlay?

**Comment by qyot27** [comment]
[AddBorders](http://avisynth.nl/index.php/AddBorders)

>ColorBars()
>ConvertToRGB24()
>Crop(0,64,0,-64)
>AddBorders(0,64,0,64)

**Comment by kaefert** [comment]
whops!
sorry for not simply trying to find that with google before asking ...
I didn't think that a direct function like that existed ;)
Thanks for the quick simple and very helpful answer :+1:

**Comment by qyot27** [comment]
ColorBars shouldn't display a BlankClip at all.  The ConvertToRGB24 was there because I originally was using odd Crop values in the example and forgot to remove it when I made them even.

If you comment out ConvertToRGB24 it really doesn't display anything?

**Comment by kaefert** [comment]
those two show colored bars by themselfs:

    ColorBars(pixel_type="YUY2")
    ColorBars(pixel_type="YV12")

those two by themselfs show only a blank (black) screen:

    ColorBars()
    ColorBars(pixel_type="RGB32")

But magically do show colored bars if you have any Convert afterwards, except `ConvertToRGB32` which doesn't change anything - but calling both

    ConvertToRGB24
    ConvertToRGB32

again does show colored bars.

**Comment by qyot27** [comment]
I wonder if maybe there's a bug with the RGB32 (or RGB general) display or rendering stuff.
