### ISSUE TITLE
avxsynth fails to build with latest ffmpeg-git

### ISSUE THREAD

**Issue by Eriner** [avxsynth/avxsynth#115]
ffmpeg-git has changed things up a bit, which causes errors like

```
src/avssources.cpp:190:29: error: ‘PIX_FMT_NONE’ was not declared in this scope
  if (TargetAVPixelFormat == PIX_FMT_NONE)
```

(PIX_FMT_NONE needs to be AV_PIX_FMT_NONE) 

and

```
src/avssources.cpp:213:24: error: ‘const FFMS_Frame {aka const struct FFMS_Frame}’ has no member named ‘ConvertedAVPixelFormat’
  TargetFormats[0] = F->ConvertedAVPixelFormat;
```

**Comment by kaefert** [comment]
I am not sure if this is related but I also cannot build avxsynth anymore. the error I get:

```
make[1]: Entering directory '/home/kaefert/src/avxsynth/plugins/avxffms2'
  CXX      src/libavxffms2_la-avisynth.lo
In file included from src/avisynth.cpp:25:0:
src/avsutils.h:30:1: error: ‘PixelFormat’ does not name a type
 PixelFormat CSNameToPIXFMT(const char *CSName, PixelFormat Default);
 ^
```

**Comment by qyot27** [comment]
So don't have it build avxffms2 with the rest of the library, which was already the answer if you wanted an FFMS2 that was at par with upstream development.  Build it separately by using the actual FFMS2 repo (checkout the c_plugin branch, use the --enable-avxsynth option).

**Comment by kaefert** [comment]
thanks for the hint. tried that, now I get a different error:

```
make[1]: Entering directory '/home/kaefert/src/avxsynth/plugins/avxffms2'
  CXX      src/libavxffms2_la-avisynth.lo
In file included from src/avisynth.cpp:24:0:
src/ffswscale.h:28:24: fatal error: ffmscompat.h: No such file or directory
compilation terminated.
Makefile:530: recipe for target 'src/libavxffms2_la-avisynth.lo' failed
```

UPDATE: ah okey, now I understood, I needed to pass the `--disable-ffms2` to the avxsynth configure script. now it works and the runtime automagically finds the ffms2 plugin built and installed from the c_plugin branch from ffms2
