### ISSUE TITLE
liblog4cpp.so.5: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by sosie-js** [avxsynth/avxsynth#125]
On debian 10, log4ccp can be installed with
`sudo apt-get install `liblog4cpp*`

but on compilation it will fail on:
`/usr/bin/ld: frameserverapp/src/avxFrameServer-main.o: undefined reference to symbol '_ZN7log4cpp8Appender29AppenderMapStorageInitializerD1Ev'
/usr/bin/ld: //usr/lib/x86_64-linux-gnu/liblog4cpp.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status`

this is due to lacking -llog4ccp in the apps/avxframeserver/Makefile, so add it here 
LIBS = -lm -ldl -llog4cpp

I assume this thing should be fixed in the configure main script

**Comment by qyot27** [comment]
No one should be using AvxSynth anymore.  It's been abandoned for years and wasn't even up-to-date by AviSynth standards when it was alive.  Even classic AviSynth 2.6 was superseded by AviSynth+ years ago, and AviSynth+ has been cross-platform for over a year now.

https://github.com/AviSynth/AviSynthPlus
https://github.com/DJATOM/avs2yuv

FFmpeg switched over to using AviSynth+ on non-Windows as of version 4.3.

**Comment by sosie-js** [comment]
Solved - project avxsynth this is outdated, avisynth+ should be prefered Thanks for your nice Pm.
