### ISSUE TITLE
running ldconfig at the end of install breaks some restricted environments

### ISSUE THREAD

**Issue by 4re** [avxsynth/avxsynth#53]
Running ldconfig is unusual practice for build script and breaks some restricted environments, such as Gentoo sandbox.

**Comment by Petross404** [comment]
@4re putting something like this:

`src_prepare() {`
`     sed -i '/ldconfig/d' relative/path/Makefile || die`
`     eapply_user`
`}`

in the ebuild, will do the trick. Mind the eapply_user, because it's EAPI6 specific (as of 2017)
